# Generated by Django 2.0.3 on 2018-03-27 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTable',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mana_cost', models.CharField(blank=True, max_length=70, null=True)),
                ('converted_mana_cost', models.CharField(blank=True, max_length=3, null=True)),
                ('types', models.CharField(blank=True, max_length=100, null=True)),
                ('card_text_mana', models.CharField(blank=True, max_length=200, null=True)),
                ('card_text', models.TextField(blank=True, null=True)),
                ('flavor_text', models.TextField(blank=True, null=True)),
                ('watermark', models.CharField(blank=True, max_length=50, null=True)),
                ('loyalty', models.CharField(blank=True, max_length=3, null=True)),
                ('p', models.CharField(blank=True, max_length=5, null=True)),
                ('t', models.CharField(blank=True, max_length=5, null=True)),
                ('expansion', models.CharField(blank=True, max_length=75, null=True)),
                ('rarity', models.CharField(blank=True, max_length=15, null=True)),
                ('all_sets', models.CharField(blank=True, max_length=10, null=True)),
                ('card_number', models.CharField(blank=True, max_length=4, null=True)),
                ('artist', models.CharField(blank=True, max_length=50, null=True)),
                ('trans_card', models.CharField(blank=True, max_length=150, null=True)),
                ('other_sets', models.CharField(blank=True, max_length=10, null=True)),
                ('color_indicator', models.CharField(blank=True, max_length=30, null=True)),
                ('linked_card', models.CharField(blank=True, max_length=50, null=True)),
                ('hand_life', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'card_table',
                'managed': False,
            },
        ),
    ]
