# Generated by Django 2.0.3 on 2018-03-29 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_deck_deckcard_shoebox'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shoebox',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoeCard', to='frontend.CardTable'),
        ),
        migrations.AlterField(
            model_name='shoebox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoeUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
